# Generated by Django 3.1.1 on 2020-10-26 05:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('experiencia', models.CharField(choices=[('Solo Maruchan', 'Solo Maruchan'), ('Primeros platos', 'Primeros platos'), ('Cocinero/a/e Amateur', 'Cocinero/a/e Amateur'), ('Chef Profesional', 'Chef Profesional')], max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('email',)},
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ingrediente_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente_nombre', models.CharField(max_length=20)),
                ('vegano', models.BooleanField(default=False)),
                ('vegetariano', models.BooleanField(default=False)),
                ('diabetico', models.BooleanField(default=False)),
                ('celiaco', models.BooleanField(default=False)),
                ('int_lactosa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('receta_nombre', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('preparacion', models.TextField(max_length=1300)),
                ('duracion', models.TimeField()),
                ('receta_foto', models.ImageField(upload_to='fotos_recetas')),
                ('fecha_publ', models.DateField(default='2020-10-26')),
                ('descripcion', models.TextField()),
                ('ingrediente', models.ManyToManyField(to='chefcitoapp.Ingrediente')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalificaReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chefcitoapp.receta')),
            ],
        ),
    ]
